version: 2
jobs:
  build:
    working_directory: ~/workspace
    docker:
      - image: circleci/openjdk:stretch-node-browsers-legacy
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - run:
          name: Install Dependencies
          command: 'npm install'
      - run: 'node_modules/.bin/firebase setup:emulators:firestore'
      - run:
          command: 'node_modules/.bin/firebase serve --only firestore'
          background: true
      - run: 'sleep 10'
      - run:
          name: Firestore Test
          command: 'npm test'
